language: cpp
os:
  - osx
compiler:
  - clang
env:
  global:
    - DEPS=""

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env:
        - DEPS="${DEPS} llvm@3.7"
        - LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake/
  allow_failures:
    - os: osx

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
        brew install ${DEPS};
    fi

script: mkdir build && cd build/ && cmake .. && make  && make test

branches:
  only:
    - master
    - travis
